logging:
  level:
    cn.binarywang.wx.miniapp: debug
    com.holland.wechatminiapp.biz: debug
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://114.115.212.83:3306/spring-cloud_gateway?serverTimezone=GMT%2B8&useSSL=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      keep-alive: true
      test-while-idle: true
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 60000
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: false
      test-on-return: false
      min-evictable-idle-time-millis: 25200000
      time-between-eviction-runs-millis: 60000
      remove-abandoned: false
      remove-abandoned-timeout: 1800
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      log-abandoned: true
  redis:
    host: localhost
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 8
        min-idle: 0
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
